### ISSUE TITLE
Hello, How Can I download a single portfolio template folder from the repository ?

### ISSUE THREAD

**Issue by hamzabahjaoui** [yasser-acc/Portfolio-websites-templates#1]

**Comment by hamzabahjaoui** [comment]
I know how to download the complete project but I am now only interested in working with a single template folder

**Comment by yasser-acc** [comment]
Hello Hamza.
To download a folder from GitHub, navigate to your desired repository in this case it is Portfolio-websites-templates, select the folder you want to download, copy the URL, navigate to <a href="https://download-directory.github.io">https://download-directory.github.io/</a> and paste the URL into the text box, and hit enter , then the download will begin 😄.

**Comment by hamzabahjaoui** [comment]
It Worked for me, Thanks ! @yasser-acc

**Comment by yasser-acc** [comment]
You are welcome!
